# **Checking PyTorch Version and GPU Availability**


## **1. Checking PyTorch Version**
- You can check the installed PyTorch version using:
  ```python
  import torch
  torch.__version__
  ```
- **Output**

  ```python
  2.5.1+cu124
  ```

## **2. Checking for GPU Availability**
- PyTorch provides `torch.cuda.is_available()` to check if a **GPU** is available.
- If a **GPU** is found, the script will print the **GPU name** and set `device` to `'cuda'`.
- If no **GPU** is available, it defaults to using the **CPU**.

### **Example**
```python
import torch

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    device = torch.device('cuda')  # Set device to GPU
else:
    print("GPU is not available. Using CPU...")
    device = torch.device('cpu')   # Set device to CPU
```
- **Output**

  ```python
  GPU is available!
  Using GPU: Tesla T4
  ```

## 3. **Creating a Tensor with Specified Values**
  - You can create a manually specified tensor using `torch.tensor()`.

  - **Example**
  ```python
  tensor_specified = torch.tensor([[1, 2, 3], [4, 5, 6]])
  print("Specified tensor:", tensor_specified)
  ```

  - **Output**
  ```python
  Specified tensor: tensor([[1, 2, 3],
                          [4, 5, 6]])
  ```

## 4. **Moving a Tensor to GPU (if available)**
- The `.to(device)` method moves a tensor to a specified device (CPU or GPU).
  - **Example**
  ```python
  gpu_tensor = tensor_specified.to(device)
  print("Tensor moved to:", device)
  ```
  - **Output**
  Tensor moved to: cuda



# **Creating Tensors in PyTorch**

## **1. Creating an Uninitialized Tensor**
### **Using `torch.empty()`**
- Creates a **tensor with uninitialized values** (random garbage values in memory).
- **Syntax:**  
  ```python
  torch.empty(size)
  ```
- **Example**
```python
torch.empty(2, 3)
```
- **Output:**
```python
tensor([[5.2421e-13, 4.3358e-41, 5.2421e-13],
        [4.3358e-41, 4.4842e-44, 0.0000e+00]])
```

## **2. Creating Tensors with Specific Values**
### **Using `torch.ones()`**
- Creates a tensor filled with zeros.
- **Syntax:**  
  ```python
  torch.ones(size)
  ```
- **Example**
```python
torch.ones(2, 3)
```
- **Output:**
```python
tensor([[1., 1., 1.],
        [1., 1., 1.]])
```


### **Using `torch.zeros()`**
- Creates a tensor filled with ones.
- **Syntax:**  
  ```python
  torch.zeros(size)
  ```
- **Example**
```python
torch.zeros(2, 3)
```
- **Output:**
```python
tensor([[0., 0., 0.],
        [0., 0., 0.]])
```

### **Using `torch.rand()`**
- Creates a tensor filled with random values between `0` and `1`.
- **Syntax:**  
  ```python
  torch.rand(size)
  ```
- **Example**
```python
torch.rand(2, 3)
```
- **Output:**
```python
tensor([[0.2876, 0.3906, 0.0459],
        [0.7114, 0.7884, 0.8450]])
```


## **3. Controlling Randomness with Seeds**
### **Using torch.manual_seed()**
- Sets the seed for reproducibility, ensuring that random values are the same each time.

- **Syntax:**  
  ```python
  torch.manual_seed(seed_value)
  ```
- **Example**
```python
# Example of using a manual seed for reproducibility
# First tensor
torch.manual_seed(100)
rand_tensor_1 = torch.rand(size=(2, 3))
print("Random tensor with seed 100:\n", rand_tensor_1)
```
- **Output:**
```python
Random tensor with seed 100:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
```

- **Example**
```python
# Second Tensor
torch.manual_seed(100)
rand_tensor_2 = torch.rand(size=(2, 3))
print("Random tensor with seed 100 again:\n", rand_tensor_2)
```
- **Output:**
```python
Random tensor with seed 100 again:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
```

## **4. Creating a Tensor with Specific Values**
### **Using `torch.tensor()`**
- Manually defines a tensor with specific values.
- **Syntax:**  
  ```python
  torch.tensor(data)
  ```
- **Example**
```python
torch.tensor([[1, 2, 3], [4, 5, 6]])
```
- **Output:**
```python
tensor([[1, 2, 3],
        [4, 5, 6]])
```

## **5. Creating Tensors with Ranges**

### **Using `torch.arange()`**
- Creates a **sequence** of numbers with a given step size.
- **Syntax:**  
  ```python
  torch.arange(start, end, step)
  ```
- **Example**
```python
torch.arange(0, 10, 2)
```
- **Output:**
```python
tensor([0, 2, 4, 6, 8])
```

### **Using `torch.linspace()`**
- Creates a **sequence** of evenly spaced numbers between `start` and `end`.
- **Syntax:**  
  ```python
  torch.linspace(start, end, steps)
  ```
- **Example**
```python
  torch.linspace(0, 10, 10)
```
- **Output:**
```python
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  
         5.5556,  6.6667,  7.7778,  8.8889, 10.0000])
```

## **6. Creating Identity Matrices**

### **Using `torch.eye()`**
- Creates an **identity matrix** (a square matrix with `1s` on the diagonal and `0s` elsewhere).
- **Syntax:**  
  ```python
  torch.eye(n)
  ```
- **Example**
```python
  torch.eye(5)
```
- **Output:**
```python
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
```

## **7. Creating a Tensor with a Fixed Value**

### **Using `torch.full()`**
- Creates a tensor filled with a **specified value**.
- **Syntax:**  
  ```python
  torch.full(size, fill_value)
```
- **Example**
```python
  torch.full((3, 3), 5)
  ```
- **Output:**
```python
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
```
## **Key Takeaways**
✔ **`torch.empty()` creates a tensor with uninitialized values (random garbage).**  
✔ **`torch.zeros()` and `torch.ones()` create tensors filled with zeros and ones, respectively.**  
✔ **`torch.rand()` generates random values between `0` and `1`.**  
✔ **`torch.manual_seed(seed_value)` ensures reproducibility by fixing random values.**  
✔ **`torch.tensor()` is used for manually specifying values in a tensor.**  
✔ **`torch.arange()` creates a range of numbers with a given step.**  
✔ **`torch.linspace()` generates evenly spaced values between a start and end point.**  
✔ **`torch.eye()` creates an identity matrix, useful in linear algebra.**  
✔ **`torch.full()` initializes a tensor with a constant value.**  






# **Tensor Shape and Initialization in PyTorch**

These functions allow you to **create new tensors** with certain properties while ensuring that the newly created tensor has the **same shape** as an existing one.

---

## **Why do we need these functions?**
- When working with tensors in **machine learning** or **deep learning**, we often need **new tensors** that have the **same shape** as an existing tensor but with different values (zeros, ones, random values, etc.).
- Instead of **manually specifying the shape** every time, PyTorch provides functions like `empty_like()`, `zeros_like()`, `ones_like()`, and `rand_like()` to quickly create new tensors that **inherit the shape** of another tensor.

---

## **What is "shape" in a tensor?**
- **Shape** defines the number of elements in each dimension of a tensor.
- For example, a tensor with **2 rows and 3 columns** has the shape **(2,3)**.
- Knowing the shape of tensors is essential for performing operations like matrix multiplication, reshaping, and data manipulation.

```python
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape) # (2, 3)
```

## **How do these functions help?**
- Suppose we have a tensor **x** with shape **(2,3)**, and we want:
  - A tensor of the **same shape** but filled with **zeros** → `torch.zeros_like(x)`
  - A tensor of the **same shape** but filled with **ones** → `torch.ones_like(x)`
  - A tensor of the **same shape** but filled with **random values** → `torch.rand_like(x)`

Instead of manually specifying the shape (`torch.zeros((2,3))`), we can simply call:

```python
torch.zeros_like(x)  # Automatically takes the shape of x
```

## **How do these functions work?**
Each function takes a **reference tensor** (an existing tensor) and returns a **new tensor** with the same shape but different values.

### **Function Breakdown**
| **Function** | **What it does** | **Concept** |
|-------------|----------------|------------|
| `x.shape` | Returns tensor shape | Used to check the dimensions of a tensor |
| `torch.empty_like(x)` | Creates a tensor with **random uninitialized values** | Placeholder tensor (values are not initialized) |
| `torch.zeros_like(x)` | Creates a tensor filled with **zeros** | Useful for initializing tensors before calculations |
| `torch.ones_like(x)` | Creates a tensor filled with **ones** | Commonly used for bias initialization |
| `torch.rand_like(x, dtype=torch.float32)` | Creates a tensor filled with **random values between 0 and 1** | Used for weight initialization in deep learning |

## **Real-World Use Cases**

### **1. Initializing Weights in Neural Networks**
- In deep learning, weight matrices are often initialized with **random values**.
- Instead of manually defining a new tensor, `torch.rand_like(x)` creates a **random tensor** with the **same shape** as an existing one.

```python
input_tensor = torch.randn(4, 5)  # A layer with 4 neurons and 5 inputs
weight_matrix = torch.rand_like(input_tensor)  # Random weights of same shape
```

### **2. Creating Masking Tensors**
- In some applications, we need to create **binary masks** (tensors filled with `0`s and `1`s) for **feature selection** or **dropout layers** in neural networks.

```python
input_tensor = torch.randn(3, 3)
mask = torch.ones_like(input_tensor)  # Create a mask of 1s for input
```

### **3. Reserving Memory Without Initializing Values**
- `torch.empty_like(x)` is used when we need a **tensor placeholder** but will **fill it with values later**.


In [ ]:
# Creating a temporary tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7234581147814279472]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## **Why does `torch.rand_like()` require a floating-point dtype?**
- `torch.rand_like()` generates **random values between 0 and 1**, which are **decimal (floating-point) numbers**.
- Integer data types (like `torch.int32` or `torch.int64`) **cannot store decimal values**, so PyTorch **needs a float dtype** to properly create the random tensor.

## **How to correctly use `torch.rand_like()`**
- If the reference tensor (`x`) is already a **floating-point type**, `torch.rand_like(x)` works **directly**.
- If the reference tensor is an **integer tensor**, you **must specify a floating-point dtype**.  

## **Example Usage**
```python
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)  # Integer tensor

# This will raise an error because x is an integer tensor
# rand_tensor = torch.rand_like(x)  ❌

# Correct way: Specify dtype as a floating-point type
rand_tensor = torch.rand_like(x, dtype=torch.float32)  # ✅
print(rand_tensor)
```

**Expected Output: **A tensor of the same shape as x, but filled with random floating-point values between `0` and `1`.

```python
tensor([[0.1342, 0.8423, 0.5761],
        [0.2983, 0.6512, 0.9134]])
```

## **Key Takeaways**
✔ **`torch.rand_like()` generates floating-point numbers** → Integer tensors **must** specify a floating-point dtype.  
✔ **Valid floating-point dtypes:** `torch.float32`, `torch.float64`, `torch.float16`.  
✔ **If the tensor is an integer type, PyTorch will raise an error unless you specify a valid dtype.**

In [ ]:
torch.rand_like(x, dtype= torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In PyTorch, every tensor has a **data type (`dtype`)**, which defines how numbers are stored and processed. Different data types are used depending on the **precision** and **memory requirements** of a model.

## **Checking the Data Type of a Tensor**
- Each tensor has a specific `dtype` that can be checked using:
  ```python
  x.dtype
  ```
- This returns the data type of `x`, helping you confirm whether the tensor is in **integer**, **floating-point**, or **boolean** format.

## **Assigning a Specific Data Type**

- When creating a tensor, you can explicitly define its data type using the `dtype` parameter:

```python
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)  # Creates an integer tensor
torch.tensor([1, 2, 3], dtype=torch.float64)  # Creates a 64-bit floating-point tensor
```

## **Changing the Data Type of an Existing Tensor**

- PyTorch provides the `.to()` function to convert a tensor to a different data type:

```python
x.to(torch.float32)  # Converts tensor x to 32-bit floating-point format
```

## **Commonly Used Data Types in PyTorch**

| **Data Type** | **PyTorch dtype** | **Description** |
|--------------|-----------------|----------------|
| **32-bit Floating Point** | `torch.float32` | Standard type for deep learning, balancing precision and memory. |
| **64-bit Floating Point** | `torch.float64` | High precision, but **uses more memory**. |
| **16-bit Floating Point** | `torch.float16` | Lower precision, used in **mixed-precision training** to save memory. |
| **8-bit Floating Point** | `torch.float8` | Experimental, extremely memory efficient. |
| **32-bit Integer** | `torch.int32` | Standard integer format for numerical operations. |
| **64-bit Integer** | `torch.int64` | Large integer values, commonly used for tensor indexing. |
| **Boolean** | `torch.bool` | Stores `True` or `False` values, often used in masks. |

## **Key Takeaways**
✔ **Tensors have a `dtype` that defines how numbers are stored.**  
✔ **You can specify the `dtype` when creating a tensor or use `.to()` to convert it later.**  
✔ **Choosing the right data type is important for balancing precision and memory usage.**  


# **Scalar Operations in PyTorch**

## **Scalar Operations in PyTorch**

### **What is a Scalar Operation?**
- A **scalar operation** is an operation where a **single scalar value** (like `2`, `3`, or `100`) is applied to **every element** in a tensor.
- These operations include **addition, subtraction, multiplication, division, modulo, and exponentiation**.

### **How do Scalar Operations Work?**
- When you perform an operation like `x + 2`, **PyTorch applies the operation to each element** in the tensor.
- The tensor **does not change shape**, only the values are modified.

---

## **Common Scalar Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Addition** | `x + 2` | Adds `2` to each element of `x`. |
| **Subtraction** | `x - 2` | Subtracts `2` from each element of `x`. |
| **Multiplication** | `x * 3` | Multiplies each element of `x` by `3`. |
| **Division** | `x / 3` | Divides each element of `x` by `3`. |
| **Integer Division** | `(x * 100) // 3` | Performs floor division after multiplying `x` by `100`. |
| **Modulo (Remainder)** | `((x * 100) // 3) % 2` | Computes remainder after integer division. |
| **Exponentiation (Power)** | `x ** 2` | Raises each element of `x` to the power of `2`. |

---

## **Example of Scalar Operations**
### **Given Tensor:**
```python
x = torch.tensor([[0.2, 0.5], [0.8, 1.0]])
```

## **Operations and Results**

| **Operation** | **Formula** | **Result** |
|--------------|------------|------------|
| **Addition** | `x + 2` | `[[2.2, 2.5], [2.8, 3.0]]` |
| **Subtraction** | `x - 2` | `[[-1.8, -1.5], [-1.2, -1.0]]` |
| **Multiplication** | `x * 3` | `[[0.6, 1.5], [2.4, 3.0]]` |
| **Division** | `x / 3` | `[[0.066, 0.166], [0.266, 0.333]]` |
| **Integer Division** | `(x * 100) // 3` | `[[6, 16], [26, 33]]` |
| **Modulo** | `((x * 100) // 3) % 2` | `[[0, 0], [0, 1]]` |
| **Exponentiation** | `x ** 2` | `[[0.04, 0.25], [0.64, 1.00]]` |

---

## **Key Takeaways**
✔ **Scalar operations apply the same operation to each element in a tensor.**  
✔ **The shape of the tensor remains unchanged, only the values are modified.**  
✔ **Operations like integer division (`//`) and modulo (`%`) are useful for indexing and discrete calculations.**  
✔ **Exponentiation (`**`) is often used in machine learning for transformations and normalization.**  


# **Element-wise Operations in PyTorch**

### **What are Element-wise Operations?**
- **Element-wise operations** apply mathematical computations to **each corresponding element** in two tensors of the **same shape**.
- These operations are **performed independently** on each element without affecting the structure of the tensor.
- If two tensors are **not the same shape**, PyTorch applies **broadcasting** to make their shapes compatible.

---

## **Common Element-wise Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Addition** | `a + b` | Adds corresponding elements of `a` and `b`. |
| **Subtraction** | `a - b` | Subtracts corresponding elements of `b` from `a`. |
| **Multiplication** | `a * b` | Multiplies corresponding elements of `a` and `b`. |
| **Division** | `a / b` | Divides corresponding elements of `a` by `b`. |
| **Exponentiation** | `a ** b` | Raises each element of `a` to the power of the corresponding element in `b`. |
| **Modulo** | `a % b` | Computes the remainder when each element in `a` is divided by `b`. |

---

## **Element-wise Absolute and Negation Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Absolute Value** | `torch.abs(c)` | Returns the absolute values of all elements in `c`. |
| **Negation** | `torch.neg(c)` | Negates each element of `c` (multiplies by `-1`). |

---

## **Element-wise Rounding Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Round** | `torch.round(d)` | Rounds each element of `d` to the nearest integer. |
| **Ceil (Ceiling)** | `torch.ceil(d)` | Rounds each element of `d` **up** to the nearest integer. |
| **Floor** | `torch.floor(d)` | Rounds each element of `d` **down** to the nearest integer. |

---

## **Clamping Values (Restricting Range)**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Clamp** | `torch.clamp(d, min=2, max=3)` | Limits all values in `d` to be between `2` and `3`. |

**Example:**
- If `d = torch.tensor([1.9, 2.3, 3.7, 4.4])`
- `torch.clamp(d, min=2, max=3)` will return: `tensor([2.0, 2.3, 3.0, 3.0])`

- Values **below `2`** are set to `2`, and values **above `3`** are set to `3`.

---

## **Key Takeaways**
✔ **Element-wise operations are performed on corresponding elements in two tensors of the same shape.**  
✔ **Broadcasting allows element-wise operations between tensors of different shapes when possible.**  
✔ **Functions like `torch.abs()`, `torch.neg()`, `torch.round()`, and `torch.clamp()` modify individual elements based on mathematical rules.**  
✔ **Clamping is useful for restricting values to a certain range, often used in activation functions and normalization.**  



# **Reduction Operations in PyTorch**

### **What are Reduction Operations?**
- **Reduction operations** compute a **single value** from a tensor by **aggregating** its elements.
- These operations **reduce** the number of dimensions by applying mathematical functions like **sum, mean, max, min, standard deviation, and variance**.
- You can **reduce an entire tensor to a scalar** or **perform reductions along a specific dimension** using the `dim` parameter.

---

## **Common Reduction Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Sum** | `torch.sum(e)` | Computes the sum of all elements in `e`. |
| **Column-wise Sum** | `torch.sum(e, dim=0)` | Sums elements **along columns** (reducing row dimension). |
| **Row-wise Sum** | `torch.sum(e, dim=1)` | Sums elements **along rows** (reducing column dimension). |
| **Mean (Average)** | `torch.mean(e)` | Computes the mean (average) of all elements in `e`. |
| **Column-wise Mean** | `torch.mean(e, dim=0)` | Computes the mean **along columns**. |
| **Median** | `torch.median(e)` | Finds the **median** of all elements in `e`. |
| **Max Value** | `torch.max(e)` | Finds the **maximum** value in `e`. |
| **Min Value** | `torch.min(e)` | Finds the **minimum** value in `e`. |
| **Product** | `torch.prod(e)` | Computes the **product** of all elements in `e`. |
| **Standard Deviation** | `torch.std(e)` | Computes the **standard deviation** of all elements. |
| **Variance** | `torch.var(e)` | Computes the **variance** of all elements. |
| **Index of Maximum Value** | `torch.argmax(e)` | Returns the **index of the max value** in `e`. |
| **Index of Minimum Value** | `torch.argmin(e)` | Returns the **index of the min value** in `e`. |

---

## **Understanding the `dim` Parameter in Reduction Operations**
- `dim=0` → **Performs reduction along columns** (collapsing rows).
- `dim=1` → **Performs reduction along rows** (collapsing columns).

### **Example**
Given tensor:
```python
e = torch.tensor([[3, 7, 1],
                  [5, 2, 8]])
```

## **Operations and Results**

| **Operation** | **Formula** | **Result** |
|--------------|------------|------------|
| **Sum of all elements** | `torch.sum(e)` | `3 + 7 + 1 + 5 + 2 + 8 = 26` |
| **Column-wise Sum** | `torch.sum(e, dim=0)` | `[3+5, 7+2, 1+8] = [8, 9, 9]` |
| **Row-wise Sum** | `torch.sum(e, dim=1)` | `[3+7+1, 5+2+8] = [11, 15]` |
| **Mean of all elements** | `torch.mean(e)` | `26 / 6 = 4.33` |
| **Max value** | `torch.max(e)` | `8` |
| **Min value** | `torch.min(e)` | `1` |
| **Index of Max Value** | `torch.argmax(e)` | `5` (index of `8`) |
| **Index of Min Value** | `torch.argmin(e)` | `2` (index of `1`) |

---

## **Key Takeaways**
✔ **Reduction operations help summarize tensor data into a single value or lower-dimensional tensors.**  
✔ **Using `dim` allows you to perform reductions along specific axes (columns or rows).**  
✔ **Standard deviation (`torch.std`) and variance (`torch.var`) measure the spread of tensor values.**  
✔ **`torch.argmax` and `torch.argmin` return the index positions of the max and min values, respectively.**  
✔ **These operations are widely used in machine learning for feature aggregation, statistics, and optimization.**  



## **Matrix Operations in PyTorch**

## **What are Matrix Operations?**
- Matrix operations are fundamental in **linear algebra** and are widely used in **machine learning**, **deep learning**, and **scientific computing**.
- These operations include **matrix multiplication, dot product, transposition, determinant, and inverse**.


## **Common Matrix Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Matrix Multiplication** | `torch.matmul(f, g)` | Multiplies two matrices following matrix multiplication rules. |
| **Dot Product (Vector Multiplication)** | `torch.dot(vector1, vector2)` | Computes the dot product between two 1D tensors (vectors). |
| **Transpose** | `torch.transpose(f, 0, 1)` | Swaps rows and columns of the matrix. |
| **Determinant** | `torch.det(h)` | Computes the determinant of a square matrix. |
| **Matrix Inverse** | `torch.inverse(h)` | Computes the inverse of a square matrix (if it exists). |


## **Understanding Matrix Multiplication (`torch.matmul`)**
- **Matrix multiplication** follows the rule:  
  - If `A` has shape **(m × n)** and `B` has shape **(n × p)**, then `C = torch.matmul(A, B)` will have shape **(m × p)**.
- The number of **columns in the first matrix** must match the **number of rows in the second matrix**.

### **Example:**
Given:
```python
f = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

g = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]])
```
Matrix multiplication `(torch.matmul(f, g))` results in:
```python
tensor([[ 58,  64],
        [139, 154]])

```
Calculation:

- First row: `(1×7) + (2×9) + (3×11)` = `58`, `(1×8) + (2×10) + (3×12)` = `64`
- Second row: `(4×7) + (5×9) + (6×11)` = `139`, `(4×8) + (5×10) + (6×12)` = `154`

## **Dot Product (`torch.dot`)**

### **Definition**
- The **dot product** is a mathematical operation that takes **two 1D tensors (vectors)** and returns a **single scalar value**.
- It is calculated by multiplying corresponding elements and then summing the results.

### **Formula**
$$
\text{dot}(a, b) = (a_1 \times b_1) + (a_2 \times b_2) + ... + (a_n \times b_n)
$$

---

### **Example**
```python
import torch

vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

result = torch.dot(vector1, vector2)  
print(result)  # Output: 1*3 + 2*4 = 11
```

### **Calculation Breakdown**
$$
(1 \times 3) + (2 \times 4) = 3 + 8 = 11
$$

---

### **Key Takeaways**
✔ **Dot product applies only to 1D tensors (vectors).**  
✔ **It produces a single scalar value.**  
✔ **The result represents a weighted sum, commonly used in machine learning, physics, and linear algebra.**  
✔ **For higher-dimensional tensors, use `torch.matmul()` or `torch.mm()` instead.**  


## **Transpose (`torch.transpose`)**

### **Definition**
- **Transpose** swaps the **rows and columns** of a matrix.
- This is useful in **linear algebra**, **image processing**, and **deep learning** when reshaping data.

### **Syntax**
```python
torch.transpose(tensor, dim0, dim1)
```

- `dim0`: The first dimension to swap.
- `dim1`: The second dimension to swap.

### **Example**

#### Given Matrix (tensor f):
```python
f = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
```
Matrix `f` looks like:

```python
tensor([[1, 2, 3],
        [4, 5, 6]])
```

#### **Applying Transpose:**

```pyhton
torch.transpose(f, 0, 1)
```


This swaps rows `(dim0=0)` and columns `(dim1=1)`, resulting in:
```python
tensor([[1, 4],
        [2, 5],
        [3, 6]])
```

### **Key Takeaways**
✔ **Transpose (`torch.transpose`) swaps matrix dimensions without changing data values.**  
✔ **It is essential in reshaping data for matrix operations like multiplication and neural networks.**  
✔ **Used frequently in image processing** (e.g., converting `Height × Width × Channels` to `Channels × Height × Width`).  
✔ **Equivalent to `.T` for 2D tensors (`tensor.T`).**  


## **Determinant (`torch.det`)**

### **Definition**
- The **determinant** is a **scalar value** that describes properties of a **square matrix** (e.g., whether it has an **inverse**).
- Only works for **square matrices** of shape `(n × n)`.
- If the determinant of a matrix is **zero**, the matrix **does not have an inverse** (i.e., it is singular).

---

### **Example**
```python
import torch

h = torch.tensor([[2, 3, 1],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float32)

result = torch.det(h)
print(result)  # Output: -3.0
```
Given Matrix (h):

```python
tensor([[2, 3, 1],
        [4, 5, 6],
        [7, 8, 9]])
```
### **Determinant Calculation**
$$
(2 \times 5 \times 9) + (3 \times 6 \times 7) + (1 \times 4 \times 8) -
(1 \times 5 \times 7) - (3 \times 4 \times 9) - (2 \times 6 \times 8) = -3
$$

---

### **Key Takeaways**
✔ **The determinant is a single scalar value computed from a square matrix.**  
✔ **If `det(A) = 0`, the matrix `A` does not have an inverse (it is singular).**  
✔ **Used in linear algebra for solving equations, checking invertibility, and understanding transformations.**  
✔ **Only works for square matrices (`n × n`).**  

## **Matrix Inverse (`torch.inverse`)**

### **Definition**
- The **inverse of a matrix** `A` is a matrix `A⁻¹` such that:
  $$
  A \times A^{-1} = I
  $$
  where `I` is the **identity matrix**.
- The inverse exists **only for square, non-singular matrices** (i.e., matrices where `det(A) ≠ 0`).
- If `det(A) = 0`, the matrix is **singular**, and `torch.inverse(A)` will fail.

---

### **Example**
```python
import torch

h = torch.tensor([[4, 7],
                  [2, 6]], dtype=torch.float32)

inverse_h = torch.inverse(h)
print(inverse_h)
```

Given Matrix (`h`):
```python
tensor([[4, 7],
        [2, 6]])
```
Inverse of `h` (`h⁻¹`):
```python
tensor([[ 0.6, -0.7],
        [-0.2,  0.4]])
```

### **Formula for Matrix Inversion**
$$
A^{-1} = \frac{1}{\det(A)} \times \text{adj}(A)
$$
where:
- **`det(A)`** is the **determinant** of `A`.
- **`adj(A)`** is the **adjugate matrix** (cofactor matrix transposed).

---

### **Key Takeaways**
✔ **The inverse of a matrix is a matrix that, when multiplied with the original, gives the identity matrix.**  
✔ **Only square matrices (`n × n`) with a nonzero determinant have an inverse.**  
✔ **If `torch.det(A) == 0`, `torch.inverse(A)` will fail because singular matrices do not have an inverse.**  
✔ **Matrix inversion is used in solving systems of equations, cryptography, and transformations in linear algebra.**  


## **Key Takeaways**
✔ **Matrix multiplication (`torch.matmul`) follows standard linear algebra rules and is essential in deep learning models.**  
✔ **Dot product (`torch.dot`) applies only to 1D tensors and computes a scalar result.**  
✔ **Transpose (`torch.transpose`) swaps matrix dimensions, useful for reshaping data.**  
✔ **Determinant (`torch.det`) helps check if a matrix is invertible.**  
✔ **Matrix inverse (`torch.inverse`) exists only for non-singular, square matrices.**  



# **In-place Operations in PyTorch**



## **What are In-place Operations?**
- **In-place operations modify the original tensor instead of creating a new one.**
- They **save memory** by avoiding the creation of new tensors but **should be used cautiously** to prevent unintended changes.
- In PyTorch, **in-place operations** are denoted by an **underscore (`_`)** at the end of the function name (e.g., `add_()`, `relu_()`).

---

## **Common In-place Operations**
| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **In-place Addition** | `m.add_(n)` | Adds `n` to `m` and modifies `m` directly. |
| **In-place ReLU Activation** | `m.relu_()` | Applies the ReLU function to `m`, replacing negative values with `0`. |

---

## **Example of In-place Operations**
```python
import torch

# Create two random tensors
m = torch.rand(2,3)
n = torch.rand(2,3)

print("Original Tensor m:\n", m)
print("Tensor n:\n", n)

# In-place addition (m is modified)
m.add_(n)
print("Tensor m after in-place addition:\n", m)

# Applying ReLU (not in-place)
torch.relu(m)  # This does NOT modify m

# Applying ReLU in-place (m is modified)
m.relu_()
print("Tensor m after in-place ReLU:\n", m)
```

## **Key Takeaways**
✔ **In-place operations modify tensors directly and save memory.**  
✔ **They are denoted by an underscore (`_`) at the end of the function name** (e.g., `add_()`, `relu_()`).  
✔ **They should be used with caution, as modifying tensors in-place can cause issues in computational graphs (autograd).**  
✔ **For non-in-place operations, use functions without `_`, like `torch.add()` and `torch.relu()`.**  


# **Copying a Tensor in PyTorch**



## **What Happens When You Assign One Tensor to Another?**
- In PyTorch, if you assign a tensor to another variable **without cloning it**, both variables **point to the same memory location**.
- Modifying one tensor **affects the other**, as they are just references to the same data.

---

## **Types of Tensor Copying**

| **Operation** | **Expression** | **Description** |
|--------------|--------------|----------------|
| **Direct Assignment** | `b = a` | `b` and `a` point to the same memory. Changes in `a` affect `b`. |
| **Cloning (Deep Copy)** | `b = a.clone()` | Creates an independent copy of `a`. Changes in `a` do **not** affect `b`. |
| **Checking Memory Location** | `id(a), id(b)` | Used to verify whether two tensors share the same memory. |

---

## **Example: Direct Assignment vs Cloning**
```python
import torch

# Create a random tensor
a = torch.rand(2,3)
print("Original Tensor a:\n", a)
```

```python
Original Tensor a:
 tensor([[0.7140, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])
```

```python
# Direct assignment (both point to the same memory)
b = a
print("Tensor b after assignment:\n", b)
```

```python
Tensor b after assignment:
 tensor([[0.7140, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])
```

```python
# Modifying 'a' affects 'b'
a[0][0] = 0
print("Tensor a after modification:\n", a)
print("Tensor b after modification:\n", b)  # b is also modified
```

```python
Tensor a after modification:
 tensor([[0.0000, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])

Tensor b after modification:
 tensor([[0.0000, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])
```

```python
# Checking memory addresses
print("Memory ID of a:", id(a))
print("Memory ID of b:", id(b))  # Same memory ID
```

```python
Memory ID of a: 132887038379696
Memory ID of b: 132887038379696
```

```python
# Cloning a tensor (creating a separate copy)
b = a.clone()
print("Tensor b after cloning:\n", b)
```

```python
Tensor b after cloning:
 tensor([[0.0000, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])
```

```python
# Modifying 'a' does not affect 'b' anymore
a[0][0] = 10
print("Tensor a after modifying cloned version:\n", a)
print("Tensor b remains unchanged:\n", b)  # b is now independent
```

```python
Tensor a after modifying cloned version:
 tensor([[10.0000,  0.4896,  0.0917],
        [ 0.3454,  0.6442,  0.4404]])
Tensor b remains unchanged:
 tensor([[0.0000, 0.4896, 0.0917],
        [0.3454, 0.6442, 0.4404]])
```

```python
# Checking memory addresses
print("Memory ID of a:", id(a))
print("Memory ID of b:", id(b))  # Different memory ID now
```

```python
Memory ID of a: 132887038379696
Memory ID of b: 132887038386416
```


## **Key Takeaways**
✔ **Direct assignment (`b = a`) makes both variables reference the same memory, so modifying one affects the other.**  
✔ **Using `a.clone()` creates a separate copy of `a`, allowing independent modifications.**  
✔ **To check if two tensors share the same memory, use `id(a) == id(b)`.**  
✔ **Cloning is essential when working with models and gradient updates to avoid unintended modifications.**  
